### ISSUE TITLE
Manage number of files saved / multithreading / progress bar

### ISSUE THREAD

**Issue by eguvep** [OpenPIV/openpiv_tk_gui#12]
Moved from Google-Groups ([https://groups.google.com/g/openpiv-users/c/agqH_b-L5KY/m/Eerqk3KKAQAJ](https://groups.google.com/g/openpiv-users/c/agqH_b-L5KY/m/Eerqk3KKAQAJ)).

Erich_...@hotmail.com wrote on, 10. September 2020 at 19:07:11 UTC+2:

    Dear Mr. Vennemann,

    Is there a way to limit the amount of files being saved during validation? When evaluating some 100 to 2000 image pairs, having five .vec files per image pair gets pretty interesting as I like to put results and images in two different folders. Additionally, should we apply multi-threading into the gui to stop the tkinter window from not responding? Perhaps we might be able to add a progress bar to see how far the PIV evaluation is (sort of like how PIVLab has a progress bar)? Sorry if this comes out like rambling. I really like PIVLab because of its preprocessing capabilities and I plan/hope OpenPIV python flavour would eventually get to the level of pre/post processing capabilities of MatLab based softwares.

    Regards,
    Erich Zimmer

    PS, is there a way in python that allows for each vector to be incorporated into an intractable point/value like in PIVLab? This can simplify manual vector validation a whole lot.

**Comment by eguvep** [comment]
Dear Erich,

1. limiting the number of files saved during validation: 
OpenPivGui now saves every validation step, because saving is much faster than asking. You can apply a filter by pressing the »< back» or »forward >« buttons to select intermediate results and either delete them (»delete files« button) or move them into a sub directory (»move files« button, new in version 0.2.6, install with pip3 install --upgrade --no-cache-dir openpivgui).

2. multithreading: 
I think multithreading would be fine. I would be happy, if you could implement that!

3. progress bar: 
I am not so sure about the progress bar. I see a danger of cluttering the code with user friendly stuff like calculating progress and calling progress bar functions. This may make the code harder to read and to understand for possible new contributors. In my opinion, it may be sufficient to insert some print statements. Most users will launch OpenPivGui from the command line anyway, I think, so they see the progress by means of the print statements.

4. allows for each vector to be incorporated into an intractable point/value: I am not sure, if I understood that correctly. Could you explain on that point?

Regards!

Peter

**Comment by ErichZimmer** [comment]
Dear Mr. Vennemann,

Thinking about your statement on the cluttering of code and keeping the GUI simple and user friendly, we should ignore statements 3 and 4. I have been searching of ways to incorporate multithreading, mainly through RxPy, but I am still a novice at programming/coding in python, so it will take a while. Meanwhile, I am testing and making sure all features I added are performing satisfactory. So far, everything seems alright and I may actually be able to create a high pass preprocessing filter if I am getting my theory correct. I am still looking at adding OpenCV2 into preprocessing for advanced image alteration, but I'm having difficulties learning from Argus 3D PTV software.

Regards,
Erich Zimmer

**Comment by alexlib** [comment]
@ErichZimmer  for multiprocessing you mind useful this part of openpiv https://github.com/OpenPIV/openpiv-python/blob/6767071f7ce462d746ac94ba13eae689146fea24/openpiv/tools.py#L362

**Comment by eguvep** [comment]
Dear Erich,

**issue 2 (multithreading):**

To run the processing part in a separate thread, it was not more that just adding lines 108 and 109 in OpenPivGui.py (version 0.2.7):

processing_thread = threading.Thread(target=self.processing)
processing_thread.start()

I would be happy, if you could test that! On my machine, it seems to work. BUT: If you now change the settings, while the processing thread is still running, the changes will take effect for all processing steps, that have not yet started. We may discuss, if this is a wanted behaviour.

**Multiprocessing**:

Multiprocessing was already implemented for the core PIV processing part from the initial version on, but not for postprocessing, because postprocessing is fairly fast using just one core.

**Issue 3 (indicating process):**

Having a separate thread now, the user interface stays responsive. We could discuss redirecting the output of print statements into another scrolled text frame at the bottom of the GUI. What do you (and other users!) think about that.?

Regards!

Peter

**Comment by ErichZimmer** [comment]
Dear Mr. Vennemann,

Maybe we could have a terminal located in the general positioned as demonstrated in this screenshot?

![Command_prompt_location](https://user-images.githubusercontent.com/69478071/92985316-062b2d80-f477-11ea-9cbc-01d5d1de966d.PNG)

Additionally, I plan on wrapping up my testing on the features I added so we could have a nice version 3.0. To shorten up the process of documenting and tutorials, I may just send demonstration pictures (most likely I won't though since that seems a little immature). I added quite a few preprocessing options and some post processing/validation, so the documentation/tutorials would take a little while.
 The multithreading is working really nicely and I really like it (gets rid of the not responding intimidation to some users). However, a timer or some limiter process must be added to the multithread to stop 'double clicking'. When the >>start processing<< was 'double clicked', the computer running the gui became unresponsive and had to be forcibly restarted.

Regards,
Erich Zimmer

**Comment by ErichZimmer** [comment]
Dear OpenPivGui Team,

I'm not sure if I'm allowed to post this in this issues forum, but before I finalize my version of the gui, I want you to have a look at some parts of it. I finished and tested all preprocessing features and also added some command line comments in the main gui class to tell the user the status of the evaluations/processes that are occuring.
![preprocessing](https://user-images.githubusercontent.com/69478071/92987351-4e524c00-f487-11ea-8bea-8fec89c8bdfe.PNG)

![return_status](https://user-images.githubusercontent.com/69478071/92987353-53170000-f487-11ea-9dfe-f8b09fc8ce70.PNG)

Some of these features may be unnecessary, but I am not able to tell yet due to my lack of theory at the moment. Finally, I hope the gui looks alright as I arranged it in a way that I deemed satisfactory.

Thanks,
Erich Zimmer

**Comment by eguvep** [comment]
**terminal window:** I think, this is a good suggestion. If we are suffering from long output lines very often, we could also spread it over the whole width, as in your last screenshot.
**documentation/demonstration pictures:** I pushed an initial reStructuredText/Sphinx documentation. See the /docs folder. You can push your images directly into the /docs/fig folder and link them in the documentation files. The final html/pdf documentation can be found on readthedocs.io: https://openpiv-tk-gui.readthedocs.io/en/latest/ It will be updated, as soon as your pull request is accepted.
**finalizing contribution:** We are only a few contributors (so far), so we do not have to be very strict about »what to discuss where«. In the standard Github philosophy, the discussion of new features is part of a pull request. You could even start a pull request without a single line of new code. Just an idea would be enough.

**Comment by ErichZimmer** [comment]
Dear Peter,

In the updated GUI, all the main features in this thread are added (including a progress bar), so I think we should close this issue.

**Comment by eguvep** [comment]
Thank you, Erich!
